src/main/java/com/project/draw/global/security/FilterConfig.java
src/main/java/com/project/draw/global/security/SecurityConfig.java
src/main/java/com/project/draw/global/security/auth/AuthDetails.java
src/main/java/com/project/draw/global/security/auth/AuthDetailsService.java

Security Config, FilterConfig
AuthDetails 생성

🔀 :: (#1) Security 설정

---

src/main/java/com/project/draw/global/security/jwt/JwtFilter.java
src/main/java/com/project/draw/global/security/jwt/JwtProperties.java
src/main/java/com/project/draw/global/security/jwt/JwtTokenProvider.java
src/main/resources/application.yml

JwtTokenProvider
JwtProperties
Jwt 검증 필터
yml 설정

🔀 :: (#2) Jwt 설정

---

src/main/java/com/project/draw/global/error/ErrorResponse.java
src/main/java/com/project/draw/global/error/GlobalExceptionFilter.java
src/main/java/com/project/draw/global/error/GlobalExceptionHandler.java
src/main/java/com/project/draw/global/error/exception/BusinessException.java
src/main/java/com/project/draw/global/error/exception/ErrorCode.java

BusinessException ErrorResponse ErrorCode
ExceptionHandler, Filter

🔀 :: (#3) Error 설정

---

src/main/java/com/project/draw/domain/user/domain/Authority.java
src/main/java/com/project/draw/domain/user/domain/User.java
src/main/java/com/project/draw/domain/user/domain/repository/UserRepository.java

🔀 :: (#5) User 엔티티

---

src/main/java/com/project/draw/domain/user/exception/UserAlreadyExistException.java
src/main/java/com/project/draw/domain/user/presentation/UserController.java
src/main/java/com/project/draw/domain/user/presentation/dto/request/LoginRequest.java
src/main/java/com/project/draw/domain/user/presentation/dto/request/SignupRequest.java
src/main/java/com/project/draw/domain/user/service/LoginService.java
src/main/java/com/project/draw/domain/user/service/SignupService.java
src/main/java/com/project/draw/global/image/DefaultImage.java

회원가입, 로그인 컨트롤러랑 서비스
유저 기본 프로필 이미지 (삭제할 수도 있음)

🔀 :: (#7) 회원가입, 로그인

---

src/main/java/com/project/draw/domain/user/exception/PasswordMismatchException.java
src/main/java/com/project/draw/domain/user/presentation/dto/request/UpdatePasswordRequest.java
src/main/java/com/project/draw/domain/user/presentation/dto/request/UpdateUserInfoRequest.java
src/main/java/com/project/draw/domain/user/service/UpdatePasswordService.java
src/main/java/com/project/draw/domain/user/service/UpdateUserInfoService.java

유저 정보(이름, 프로필 이미지), 비밀번호 수정 api, 서비스 로직

🔀 :: (#9) 유저 정보 수정

---

src/main/java/com/project/draw/domain/user/service/LogoutService.java
src/main/java/com/project/draw/domain/user/service/TokenRefreshService.java
src/main/java/com/project/draw/domain/user/service/WithdrawalService.java

LogoutService WithdrawalService

🔀 :: (#19) 유저 로그아웃, 탈퇴

---

src/main/java/com/project/draw/domain/post/domain/Post.java
src/main/java/com/project/draw/domain/post/domain/Tag.java
src/main/java/com/project/draw/domain/post/domain/repository/PostRepository.java
src/main/java/com/project/draw/global/entity/BaseTimeEntity.java

📝 :: (#6) Post, PostRepository

---

src/main/java/com/project/draw/domain/user/domain/User.java
src/main/java/com/project/draw/domain/user/presentation/dto/request/SignupRequest.java
src/main/java/com/project/draw/domain/user/service/SignupService.java

🔀 :: (#20) 유저 이메일 정보 추가

---

src/main/java/com/project/draw/domain/post/domain/repository/PostRepository.java
src/main/java/com/project/draw/domain/post/presentation/PostController.java
src/main/java/com/project/draw/domain/post/presentation/dto/request/CreatePostRequest.java
src/main/java/com/project/draw/domain/post/service/CreatePostService.java

✨ :: (#30) 게시글 생성 Api 추가

---

src/main/java/com/project/draw/domain/post/domain/repository/PostRepository.java
src/main/java/com/project/draw/domain/post/exception/InvalidUserException.java
src/main/java/com/project/draw/domain/post/exception/PostNotFoundException.java
src/main/java/com/project/draw/domain/post/facade/Postfacade.java
src/main/java/com/project/draw/domain/post/presentation/PostController.java
src/main/java/com/project/draw/domain/post/presentation/dto/request/CreatePostRequest.java
src/main/java/com/project/draw/domain/post/presentation/dto/request/UpdatePostRequest.java
src/main/java/com/project/draw/domain/post/service/CreatePostService.java
src/main/java/com/project/draw/domain/post/service/UpdatePostService.java
src/main/java/com/project/draw/global/error/exception/ErrorCode.java

✨ :: (#32) 게시글 수정 Api 구현

---

src/main/java/com/project/draw/domain/post/service/CreatePostService.java
src/main/java/com/project/draw/domain/post/service/UpdatePostService.java

🐛 :: (#35) 서비스에 트랜잭션 추가

---

src/main/java/com/project/draw/domain/post/domain/repository/PostRepository.java
src/main/java/com/project/draw/domain/post/presentation/PostController.java
src/main/java/com/project/draw/domain/post/presentation/dto/response/PostListResponse.java
src/main/java/com/project/draw/domain/post/service/QueryMyPostService.java

✨ :: (#37) 내 게시글 조회 Api 구현

---

src/main/java/com/project/draw/domain/post/facade/Postfacade.java
src/main/java/com/project/draw/domain/post/presentation/PostController.java
src/main/java/com/project/draw/domain/post/service/QueryMyPostService.java
src/main/java/com/project/draw/domain/post/service/QueryPostsService.java
src/main/java/com/project/draw/domain/post/service/UpdatePostService.java

♻️ :: (#41) PostFacade로 이름 변경

---

src/main/java/com/project/draw/domain/post/presentation/PostController.java
src/main/java/com/project/draw/domain/post/service/QueryMyPostService.java
src/main/java/com/project/draw/domain/post/service/QueryPostsService.java

✨ :: (#39) 게시글 전체조회 Api 구현

---

src/main/java/com/project/draw/domain/user/domain/User.java

♻️ :: (#26) 유저 생성자, 빌더

---

src/main/java/com/project/draw/domain/image/presentation/ImageController.java
src/main/java/com/project/draw/domain/image/presentation/dto/response/ImagesUrlResponse.java
src/main/java/com/project/draw/domain/image/service/ImagesUploadService.java
src/main/java/com/project/draw/global/error/exception/ErrorCode.java
src/main/java/com/project/draw/global/exception/ImageSaveException.java
src/main/java/com/project/draw/global/exception/ImageValueNotFoundException.java
src/main/java/com/project/draw/global/image/s3/S3Facade.java
src/main/java/com/project/draw/global/image/s3/S3Properties.java
src/main/resources/application.yml

⚡ :: (#27) 유저 프로필 이미지 저장

---

src/main/java/com/project/draw/domain/post/domain/repository/PostRepository.java
src/main/java/com/project/draw/domain/post/presentation/PostController.java
src/main/java/com/project/draw/domain/post/service/DeletePostService.java
src/main/java/com/project/draw/domain/post/service/QueryPostByTagService.java

✨ :: (#50) 게시글 삭제 Api 구현

---

src/main/java/com/project/draw/domain/user/domain/User.java
src/main/java/com/project/draw/domain/user/presentation/UserController.java
src/main/java/com/project/draw/domain/user/presentation/dto/request/UpdateEmailRequest.java
src/main/java/com/project/draw/domain/user/presentation/dto/response/QueryUserInfoResponse.java
src/main/java/com/project/draw/domain/user/service/QueryMyInfoService.java
src/main/java/com/project/draw/domain/user/service/QueryUserInfoService.java
src/main/java/com/project/draw/domain/user/service/UpdateEmailService.java

⚡ :: 아이디 찾기 삭제, 이메일 수정

---

src/main/java/com/project/draw/domain/post/facade/PostFacade.java
src/main/java/com/project/draw/domain/post/service/DeletePostService.java
src/main/java/com/project/draw/domain/post/service/QueryPostInfoService.java
src/main/java/com/project/draw/domain/post/service/UpdatePostService.java

♻️ :: (#52) getById()로 메소드명 수정

---

src/main/java/com/project/draw/domain/auth/domain/repository/RefreshTokenRepository.java
src/main/java/com/project/draw/domain/user/domain/User.java
src/main/java/com/project/draw/domain/user/facade/UserFacade.java
src/main/java/com/project/draw/domain/user/presentation/dto/request/UpdateUserInfoRequest.java
src/main/java/com/project/draw/domain/user/service/LogoutService.java
src/main/java/com/project/draw/domain/user/service/SendSignupAuthCodeService.java
src/main/java/com/project/draw/domain/user/service/SignupService.java

♻️ :: (#61) 기타 리팩토링

---

src/main/java/com/project/draw/domain/post/domain/repository/PostRepository.java
src/main/java/com/project/draw/domain/post/presentation/PostController.java
src/main/java/com/project/draw/domain/post/service/QueryPostByKeywordService.java

✨ :: (#56) 게시글 검색 Api 구현

---

build.gradle
src/main/java/com/project/draw/domain/auth/presentation/GoogleController.java
src/main/java/com/project/draw/domain/auth/service/GoogleAuthService.java
src/main/java/com/project/draw/global/error/exception/ErrorCode.java
src/main/java/com/project/draw/global/properties/AuthProperties.java
src/main/java/com/project/draw/global/util/auth/service/QueryGoogleAuthLinkService.java
src/main/java/com/project/draw/infrastructure/feign/FeignClientErrorDecoder.java
src/main/java/com/project/draw/infrastructure/feign/FeignConfig.java
src/main/java/com/project/draw/infrastructure/feign/client/GoogleAuth.java
src/main/java/com/project/draw/infrastructure/feign/client/GoogleInfo.java
src/main/java/com/project/draw/infrastructure/feign/dto/request/CodeRequest.java
src/main/java/com/project/draw/infrastructure/feign/dto/request/GoogleCodeRequest.java
src/main/java/com/project/draw/infrastructure/feign/dto/response/GoogleInfoResponse.java
src/main/java/com/project/draw/infrastructure/feign/dto/response/TokenResponse.java
src/main/java/com/project/draw/infrastructure/feign/exception/OtherBadRequestException.java
src/main/java/com/project/draw/infrastructure/feign/exception/OtherExpiredTokenException.java
src/main/java/com/project/draw/infrastructure/feign/exception/OtherForbiddenException.java
src/main/java/com/project/draw/infrastructure/feign/exception/OtherUnAuthorizedException.java
src/main/resources/application.yml

✨ :: (#66) 구글 로그인 Api 추가

---

src/main/java/com/project/draw/domain/post/presentation/PostController.java
src/main/java/com/project/draw/domain/post/service/DeletePostService.java

🔀 :: (#68) deletePost 유저 체크

---

Dockerfile

🔧 :: Dockerfile

---

src/main/java/com/project/draw/domain/post/presentation/PostController.java

🐛 :: (#76)핸들러 중복

---

src/main/java/com/project/draw/global/security/jwt/JwtTokenProvider.java

♻️ :: (#77) jwt deprecated된 signWith메서드 대체

---

build.gradle
src/main/resources/application.yml

🔀 :: (#82) sentry 추가

---

src/main/java/com/project/draw/domain/auth/service/GoogleAuthService.java
src/main/java/com/project/draw/domain/post/domain/Tag.java
src/main/java/com/project/draw/domain/post/presentation/PostController.java
src/main/java/com/project/draw/domain/post/presentation/dto/response/PostResponse.java
src/main/java/com/project/draw/global/image/DefaultImage.java
src/main/java/com/project/draw/global/security/jwt/JwtTokenProvider.java

🔀 :: (#87) api명세서랑 안맞는 부분 수정

---

src/main/java/com/project/draw/global/security/SecurityConfig.java

♻️ :: (#91) 인가 범위, config 방식 수정

---

src/main/java/com/project/draw/domain/user/service/SendAuthCodeService.java
src/main/java/com/project/draw/domain/user/service/SignupService.java

🔀 :: (#92)이메일 도메인 체크

---

src/main/java/com/project/draw/domain/auth/service/GoogleAuthService.java
src/main/java/com/project/draw/domain/post/presentation/dto/response/PostInfoResponse.java
src/main/java/com/project/draw/domain/post/presentation/dto/response/PostResponse.java
src/main/java/com/project/draw/domain/post/service/QueryPostInfoService.java
src/main/java/com/project/draw/global/security/AuthProperties.java
src/main/java/com/project/draw/global/util/auth/service/QueryGoogleAuthLinkService.java
src/main/java/com/project/draw/global/util/date/DateUtil.java

🔀 :: (#97) Post 등록 시간 포맷팅

---

src/main/java/com/project/draw/domain/chat/domain/Chat.java
src/main/java/com/project/draw/domain/chat/domain/Room.java
src/main/java/com/project/draw/domain/chat/domain/RoomUser.java
src/main/java/com/project/draw/domain/chat/domain/RoomUserId.java
src/main/java/com/project/draw/domain/chat/domain/enums/RoomType.java
src/main/java/com/project/draw/domain/chat/domain/repository/ChatRepository.java
src/main/java/com/project/draw/domain/chat/domain/repository/RoomRepository.java
src/main/java/com/project/draw/domain/chat/domain/repository/RoomUserRepository.java
src/main/java/com/project/draw/domain/chat/exception/RoomNotFoundException.java
src/main/java/com/project/draw/domain/chat/exception/RoomUserNotFoundException.java
src/main/java/com/project/draw/domain/chat/facade/RoomFacade.java
src/main/java/com/project/draw/domain/chat/facade/RoomUserFacade.java
src/main/java/com/project/draw/domain/chat/presentation/ChatController.java
src/main/java/com/project/draw/domain/chat/presentation/ChatSocketController.java
src/main/java/com/project/draw/domain/chat/presentation/dto/request/SendChatRequest.java
src/main/java/com/project/draw/domain/chat/presentation/dto/response/QueryChatListResponse.java
src/main/java/com/project/draw/domain/chat/service/QueryChatListService.java
src/main/java/com/project/draw/domain/chat/service/QueryMyRoomListService.java
src/main/java/com/project/draw/domain/chat/service/SendChatService.java
src/main/java/com/project/draw/global/error/exception/ErrorCode.java
src/main/java/com/project/draw/global/exception/ForbiddenException.java
src/main/java/com/project/draw/global/socket/SocketConnectListener.java
src/main/java/com/project/draw/global/socket/SocketProperty.java
src/main/java/com/project/draw/global/socket/SocketRunner.java
src/main/java/com/project/draw/global/socket/WebSocketConfig.java
src/main/java/com/project/draw/global/socket/exception/SocketExceptionListener.java
src/main/java/com/project/draw/global/socket/security/ClientProperty.java
src/main/java/com/project/draw/global/socket/util/SocketUtil.java

🔀 :: (#96) netty-socketio 채팅 기능

---

build.gradle
src/main/java/com/project/draw/domain/project/domain/Project.java
src/main/java/com/project/draw/domain/project/domain/ProjectInvitation.java
src/main/java/com/project/draw/domain/project/domain/ProjectUser.java
src/main/java/com/project/draw/domain/project/domain/ProjectUserId.java
src/main/java/com/project/draw/domain/project/domain/enums/ProjectUserType.java
src/main/java/com/project/draw/domain/project/domain/repository/ProjectInvitationRepository.java
src/main/java/com/project/draw/domain/project/domain/repository/ProjectRepository.java
src/main/java/com/project/draw/domain/project/domain/repository/ProjectUserRepository.java
src/main/java/com/project/draw/domain/project/exception/UserNotInvitedException.java
src/main/java/com/project/draw/domain/project/facade/ProjectFacade.java
src/main/java/com/project/draw/domain/project/presentation/ProjectController.java
src/main/java/com/project/draw/domain/project/presentation/dto/request/AcceptInviteRequest.java
src/main/java/com/project/draw/domain/project/presentation/dto/request/CreateProjectRequest.java
src/main/java/com/project/draw/domain/project/presentation/dto/request/InviteUserRequest.java
src/main/java/com/project/draw/domain/project/presentation/dto/request/LeaveProjectRequest.java
src/main/java/com/project/draw/domain/project/presentation/dto/response/CreateProjectResponse.java
src/main/java/com/project/draw/domain/project/presentation/dto/response/QueryProjectInfoResponse.java
src/main/java/com/project/draw/domain/project/service/AcceptInviteService.java
src/main/java/com/project/draw/domain/project/service/CreateProjectService.java
src/main/java/com/project/draw/domain/project/service/InviteUserService.java
src/main/java/com/project/draw/domain/project/service/LeaveProjectService.java
src/main/java/com/project/draw/domain/project/service/QueryProjectInfoService.java
src/main/java/com/project/draw/domain/user/facade/UserFacade.java
src/main/java/com/project/draw/domain/user/presentation/dto/response/UserResponse.java
src/main/java/com/project/draw/global/security/jwt/JwtTokenProvider.java

🔀 :: (#95) 프로젝트 엔티티 생성 + 프로젝트 만들기 기능

---

build.gradle
src/test/java/com/project/draw/constant/ProjectConstant.java
src/test/java/com/project/draw/constant/RoomConstant.java
src/test/java/com/project/draw/constant/UserConstant.java
src/test/java/com/project/draw/domain/project/service/CreateProjectServiceTest.java
src/test/java/com/project/draw/util/ProjectBuilder.java
src/test/java/com/project/draw/util/RoomBuilder.java
src/test/java/com/project/draw/util/UserBuilder.java

🔀 :: (#102) 프로젝트 테스트코드

---

src/main/java/com/project/draw/domain/chat/domain/Room.java

🔀 :: (#101) 채팅방 목록 조회

---

src/main/java/com/project/draw/domain/post/domain/Post.java
src/main/java/com/project/draw/domain/post/presentation/dto/request/CreatePostRequest.java
src/main/java/com/project/draw/domain/post/presentation/dto/request/UpdatePostRequest.java
src/main/java/com/project/draw/domain/post/presentation/dto/response/PostInfoResponse.java
src/main/java/com/project/draw/domain/post/presentation/dto/response/PostResponse.java

🔀 :: (#105) 게시글에 완료여부 추가

---

src/main/java/com/project/draw/domain/post/domain/Like.java
src/main/java/com/project/draw/domain/post/domain/LikeUserId.java
src/main/java/com/project/draw/domain/post/domain/Post.java
src/main/java/com/project/draw/domain/post/domain/repository/LikeRepository.java
src/main/java/com/project/draw/domain/post/presentation/LikeController.java
src/main/java/com/project/draw/domain/post/service/AddLikeService.java
src/main/java/com/project/draw/domain/post/service/DeleteLikeService.java
src/main/java/com/project/draw/domain/post/service/DeletePostService.java

✨ :: (#110)좋아요 추가/삭제 Api 구현

---

.github/workflow/ci.yml
build.gradle

⚡ :: (#112)SonarCloud 추가

---

src/main/java/com/project/draw/domain/post/domain/Post.java
src/main/java/com/project/draw/domain/post/domain/repository/PostRepository.java
src/main/java/com/project/draw/domain/post/presentation/PostController.java
src/main/java/com/project/draw/domain/post/service/QueryMyPostService.java
src/main/java/com/project/draw/domain/post/service/QueryPostInfoService.java
src/main/java/com/project/draw/domain/post/service/QueryPostsService.java

🔀 :: (#109) sort 파라미터로 받기 

---

.github/workflow/CD.yml
.github/workflow/CI.yml

🔀 :: (#117) CI/CD 구축

---

src/main/java/com/project/draw/domain/post/domain/Like.java
src/main/java/com/project/draw/domain/post/domain/Post.java
src/main/java/com/project/draw/domain/post/domain/repository/LikeRepository.java
src/main/java/com/project/draw/domain/post/facade/LikeFacade.java
src/main/java/com/project/draw/domain/post/presentation/LikeController.java
src/main/java/com/project/draw/domain/post/presentation/PostController.java
src/main/java/com/project/draw/domain/post/presentation/dto/response/PostInfoResponse.java
src/main/java/com/project/draw/domain/post/presentation/dto/response/PostResponse.java
src/main/java/com/project/draw/domain/post/service/DeletePostService.java
src/main/java/com/project/draw/domain/post/service/QueryMyPostService.java
src/main/java/com/project/draw/domain/post/service/QueryPostsByKeywordService.java
src/main/java/com/project/draw/domain/post/service/QueryPostsByTagService.java
src/main/java/com/project/draw/domain/post/service/QueryPostsInfoService.java

🔀 :: (#116) 좋아요 갯수 조회 추가

---

.github/workflow/CD.yml
src/main/java/com/project/draw/DrawApplication.java
src/main/java/com/project/draw/domain/chat/presentation/dto/response/ChatResponse.java
src/main/java/com/project/draw/domain/post/domain/Post.java
src/main/java/com/project/draw/domain/post/presentation/dto/response/PostResponse.java
src/main/java/com/project/draw/domain/user/domain/User.java
src/main/java/com/project/draw/global/entity/BaseTimeEntity.java
src/main/java/com/project/draw/global/util/jms/JmsUtil.java
src/main/resources/application.yml
src/test/java/com/project/draw/domain/FailTest.java

 🔀 :: (#124) 서버시간 한국기준으로

---

LICENSE

📝 :: (#140)LICENSE 추가

---

LICENSE
src/main/java/com/project/draw/domain/image/service/ImagesUploadService.java
src/main/java/com/project/draw/domain/post/service/AddLikeService.java
src/main/java/com/project/draw/domain/post/service/DeleteLikeService.java
src/main/java/com/project/draw/domain/post/service/DeletePostService.java
src/main/java/com/project/draw/domain/post/service/QueryPostInfoService.java
src/main/java/com/project/draw/domain/post/service/QueryPostsInfoService.java
src/main/java/com/project/draw/domain/post/service/QueryTagsService.java
src/main/java/com/project/draw/domain/user/service/LoginService.java
src/main/java/com/project/draw/domain/user/service/SendAuthCodeService.java
src/main/java/com/project/draw/domain/user/service/SendSignupAuthCodeService.java
src/main/java/com/project/draw/domain/user/service/VerifyAuthCodeService.java

⚡ :: (#139)트랜잭션 추가

---

src/main/java/com/project/draw/domain/chat/presentation/ChatController.java
src/main/java/com/project/draw/domain/chat/presentation/dto/request/JoinSocketRoomRequest.java
src/main/java/com/project/draw/domain/chat/presentation/dto/request/SendChatRequest.java
src/main/java/com/project/draw/domain/chat/service/JoinSocketRoomService.java
src/main/java/com/project/draw/domain/chat/service/SendChatService.java
src/main/java/com/project/draw/domain/post/domain/enums/Tag.java
src/main/java/com/project/draw/domain/user/domain/User.java
src/main/java/com/project/draw/domain/user/facade/UserFacade.java
src/main/java/com/project/draw/global/socket/SocketConnectListener.java
src/main/java/com/project/draw/global/socket/facade/SocketRoomFacade.java
src/main/java/com/project/draw/global/socket/util/SocketUtil.java

🔀 :: (#133) 마지막 채팅 읽음 여부 갱신 

---

src/main/java/com/project/draw/domain/chat/presentation/dto/response/ChatResponse.java
src/main/java/com/project/draw/domain/post/service/QueryPostInfoService.java
src/main/java/com/project/draw/domain/user/presentation/dto/response/UserResponse.java
src/main/java/com/project/draw/global/util/date/DateUtil.java

🔀 :: (#143) isliked 조회 오류

---

src/main/java/com/project/draw/domain/user/presentation/dto/request/UpdateUserInfoRequest.java

🐛 :: (#145) name으로 수정

---

src/main/java/com/project/draw/domain/user/domain/User.java
src/main/java/com/project/draw/domain/user/presentation/dto/request/UpdateUserInfoRequest.java

🔀 :: (#149) 유저 정보 업데이트 버그

---

src/main/java/com/project/draw/global/security/SecurityConfig.java

🔀 :: (#151)게시글 목록 조회 권한 permitAll

---

src/main/java/com/project/draw/global/web/WebMvcConfig.java

🐛 :: (#156) AllowedCredentials(true)
